global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'speech-ai'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['speech-ai:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'speech-ai-hexagonal'