name: Testes + SonarQube + Codecov
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Cache SonarQube packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Setup Testcontainers Cloud
        uses: atomicjar/testcontainers-cloud-setup-action@7d1bab3fdfe0027c91936deca6b924d8a8a7a04d
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Build + Testes + JaCoCo
        run: ./gradlew clean build --continue --no-daemon --quiet

      - name: SonarCloud
        if: success() || failure()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --no-daemon --info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results

      - name: Upload relatório JaCoCo (artifact)
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/
          retention-days: 14